### ISSUE TITLE
"Files on SMB-share corrupted while up- and downloading"

### ISSUE THREAD

**Issue by alexpovel** [icewind1991/SMB#104] opened 2021-04-16 09:17 UTC
Hi,

haven't seen an open issue on this here, so I wanted to raise awareness. In Nextcloud (Server), there is currently this issue: https://github.com/nextcloud/server/issues/26457 . This repository seems to be the upstream source for those problems. For example, [one user posted their error log](https://github.com/nextcloud/server/issues/26457#issuecomment-816592648). It seems [release 3.4 might have introduced the issue](https://github.com/nextcloud/server/issues/26457#issuecomment-821034060).

**Comment by danielnachtrub** [comment] 2021-04-18 18:01
Yes, the issue is located in StringBuffer read - offset on subsequent reads with position > 0 will return incorrect data.

`$chunk = substr($this->buffer, $this->pos, $count);`

**Comment by icewind1991** [comment] 2021-04-19 13:59
fixed with 3.4.1 thanks @danielnachtrub

**Closed by icewind1991** 2021-04-19 13:59 UTC
